import type { TeamListItem, TeamListItemPayload } from '../shared/types.js'

export const serializeTeamListItem = ({
  args,
  command,
  commandPresetId,
  currentTaskId,
  currentTaskStatus,
  currentTaskTitle,
  description,
  hasActiveRun,
  id,
  lastArtifactAt,
  lastDeliveredAt,
  lastDispatchedAt,
  lastFailure,
  lastPtyLine,
  lastPtyOutputAt,
  lifecycleStatus,
  minutesSinceLastArtifact,
  name,
  paused,
  pendingTaskCount,
  role,
  rssMb,
  status,
}: TeamListItem): TeamListItemPayload => ({
  id,
  name,
  role,
  status,
  pending_task_count: pendingTaskCount,
  last_pty_line: lastPtyLine ?? null,
  command_preset_id: commandPresetId ?? null,
  command: command ?? null,
  args: args ?? null,
  description: description ?? null,
  last_pty_output_at: lastPtyOutputAt ?? null,
  last_dispatched_at: lastDispatchedAt ?? null,
  last_delivered_at: lastDeliveredAt ?? null,
  has_active_run: hasActiveRun ?? false,
  paused: paused ?? false,
  current_task_id: currentTaskId ?? null,
  current_task_title: currentTaskTitle ?? null,
  current_task_status: currentTaskStatus ?? null,
  ...(lifecycleStatus ? { lifecycle_status: lifecycleStatus } : {}),
  // Orchestrator feedback #2/#3: failure reason + file-activity clock.
  ...(lastFailure ? { last_failure: lastFailure } : {}),
  ...(lastArtifactAt !== undefined ? { last_artifact_at: lastArtifactAt } : {}),
  ...(minutesSinceLastArtifact !== undefined
    ? { minutes_since_last_artifact: minutesSinceLastArtifact }
    : {}),
  ...(rssMb !== undefined && rssMb !== null ? { rss_mb: rssMb } : {}),
})
