import type { WorkerRole } from '../../../src/shared/types.js'
import type { UiLanguage } from '../uiLanguage.js'

/* Worker names are historical figures. Each role draws from a flavor-matched
   pool (Coder = artisans/inventors, Reviewer = jurists/philosophers, Tester =
   explorers/experimentalists). The Custom role draws from a much larger
   union that also includes the OTHERS pool — emperors, generals, poets,
   composers, novelists, painters — so picking "custom" is also a way of
   asking for the broadest possible cast.

   Names are returned bare (no numeric suffix). Multi-word English names use
   hyphens (`marcus-aurelius`) so they survive `team send <name>` without
   quoting. We stay on figures widely recognized as cultural staples and
   skip 20th-century political figures plus living people; a handful of
   computing pioneers (Turing, Hopper, Ritchie, von Neumann, Shannon) earn
   a pass for being patron saints of the craft.

   English pools stay within the Greco-Roman / European / Anglo-American
   sphere; Chinese pools stay within the Chinese cultural sphere. This
   avoids the "who counts as which tradition" arguments that pop up the
   moment you mix traditions in the same bucket.

   Pools are sorted (ASCII for `en`, pinyin for `zh`) so adding a name
   shifts only entries after the insertion point — keeps snapshot tests
   stable.
*/

const EN_CODER = [
  'ada-lovelace',
  'archimedes',
  'babbage',
  'bell',
  'bernoulli',
  'bessemer',
  'boole',
  'cantor',
  'cardano',
  'da-vinci',
  'daguerre',
  'diesel',
  'edison',
  'eiffel',
  'euclid',
  'euler',
  'fermat',
  'fibonacci',
  'fourier',
  'fulton',
  'galois',
  'gauss',
  'gutenberg',
  'hertz',
  'hilbert',
  'hopper',
  'hypatia',
  'jacquard',
  'lagrange',
  'laplace',
  'leibniz',
  'marconi',
  'maxwell',
  'morse',
  'nobel',
  'noether',
  'otto',
  'pascal',
  'poincare',
  'pythagoras',
  'riemann',
  'ritchie',
  'shannon',
  'siemens',
  'stephenson',
  'tesla',
  'turing',
  'von-neumann',
  'watt',
  'westinghouse',
  'wright-brothers',
] as const

const EN_REVIEWER = [
  'adam-smith',
  'anaximander',
  'anselm',
  'aquinas',
  'aristotle',
  'augustine',
  'bacon',
  'bentham',
  'blackstone',
  'burke',
  'calvin',
  'cicero',
  'democritus',
  'descartes',
  'diogenes',
  'epictetus',
  'epicurus',
  'erasmus',
  'gibbon',
  'grotius',
  'hegel',
  'heraclitus',
  'herodotus',
  'hobbes',
  'hume',
  'justinian',
  'kant',
  'kierkegaard',
  'locke',
  'luther',
  'machiavelli',
  'marcus-aurelius',
  'mill',
  'montaigne',
  'montesquieu',
  'nietzsche',
  'ockham',
  'parmenides',
  'plato',
  'rousseau',
  'schopenhauer',
  'seneca',
  'socrates',
  'solon',
  'spinoza',
  'tacitus',
  'thales',
  'thucydides',
  'voltaire',
  'wollstonecraft',
] as const

const EN_TESTER = [
  'amundsen',
  'avogadro',
  'bering',
  'boyle',
  'brahe',
  'cartier',
  'cavendish',
  'champlain',
  'cook',
  'copernicus',
  'curie',
  'da-gama',
  'dalton',
  'darwin',
  'drake',
  'eratosthenes',
  'erikson',
  'faraday',
  'fleming',
  'galen',
  'galileo',
  'hahn',
  'halley',
  'harvey',
  'hippocrates',
  'hooke',
  'humboldt',
  'huygens',
  'jenner',
  'joule',
  'kepler',
  'koch',
  'lavoisier',
  'leeuwenhoek',
  'linnaeus',
  'lyell',
  'magellan',
  'marco-polo',
  'mendel',
  'mendeleev',
  'newton',
  'ohm',
  'paracelsus',
  'pasteur',
  'planck',
  'priestley',
  'ptolemy',
  'rutherford',
  'scott',
  'shackleton',
  'vesalius',
  'volta',
] as const

/* Emperors, generals, poets, novelists, composers, painters — household
   names that don't slot neatly into Coder/Reviewer/Tester but should still
   show up when the user picks "Custom". */
const EN_OTHERS = [
  'aeschylus',
  'alexander',
  'augustus',
  'austen',
  'bach',
  'beethoven',
  'boccaccio',
  'botticelli',
  'brahms',
  'byron',
  'caesar',
  'caravaggio',
  'cervantes',
  'charlemagne',
  'chaucer',
  'chopin',
  'cleopatra',
  'constantine',
  'dante',
  'debussy',
  'defoe',
  'degas',
  'dickens',
  'donatello',
  'dostoevsky',
  'dumas',
  'einstein',
  'el-greco',
  'elizabeth-i',
  'emerson',
  'euripides',
  'franklin',
  'frederick',
  'gauguin',
  'goethe',
  'goya',
  'handel',
  'hannibal',
  'henry-viii',
  'homer',
  'hugo',
  'ibsen',
  'jefferson',
  'joan-of-arc',
  'keats',
  'leonidas',
  'lincoln',
  'liszt',
  'louis-xiv',
  'mahler',
  'manet',
  'matisse',
  'melville',
  'mendelssohn',
  'michelangelo',
  'milton',
  'monet',
  'mozart',
  'napoleon',
  'nelson',
  'nightingale',
  'orwell',
  'ovid',
  'paine',
  'peter-the-great',
  'petrarch',
  'picasso',
  'poe',
  'pushkin',
  'raphael',
  'ravel',
  'rembrandt',
  'rodin',
  'rubens',
  'sappho',
  'schiller',
  'schubert',
  'schumann',
  'shakespeare',
  'shelley',
  'sophocles',
  'swift',
  'tchaikovsky',
  'tennyson',
  'thoreau',
  'titian',
  'tolstoy',
  'trajan',
  'twain',
  'van-gogh',
  'velazquez',
  'verdi',
  'vermeer',
  'virgil',
  'vivaldi',
  'wagner',
  'washington',
  'whitman',
  'wilde',
  'woolf',
  'wordsworth',
  'yeats',
] as const

const ZH_CODER = [
  '八大山人',
  '毕昇',
  '蔡伦',
  '蔡邕',
  '程大位',
  '杜诗',
  '范宽',
  '干将',
  '顾恺之',
  '郭守敬',
  '怀素',
  '黄道婆',
  '黄公望',
  '贾思勰',
  '李冰',
  '李春',
  '李诫',
  '柳公权',
  '刘徽',
  '鲁班',
  '马钧',
  '米芾',
  '莫邪',
  '墨子',
  '倪瓒',
  '欧冶子',
  '秦九韶',
  '僧一行',
  '沈括',
  '宋应星',
  '苏颂',
  '唐寅',
  '王希孟',
  '王羲之',
  '卫夫人',
  '文徵明',
  '吴道子',
  '阎立本',
  '颜真卿',
  '杨辉',
  '喻皓',
  '张衡',
  '张择端',
  '赵孟頫',
  '郑板桥',
  '周昉',
  '朱思本',
  '朱载堉',
  '祖冲之',
  '祖暅',
] as const

const ZH_REVIEWER = [
  '班固',
  '包拯',
  '戴震',
  '邓析',
  '狄仁杰',
  '董仲舒',
  '范缜',
  '范仲淹',
  '公孙弘',
  '龚自珍',
  '顾炎武',
  '管仲',
  '海瑞',
  '韩非',
  '韩愈',
  '何休',
  '黄宗羲',
  '嵇康',
  '贾谊',
  '孔子',
  '寇准',
  '老子',
  '列子',
  '林则徐',
  '柳宗元',
  '陆九渊',
  '孟子',
  '欧阳修',
  '商鞅',
  '申不害',
  '史可法',
  '司马光',
  '司马迁',
  '宋慈',
  '谭嗣同',
  '王安石',
  '王充',
  '王夫之',
  '王守仁',
  '魏徵',
  '荀子',
  '杨朱',
  '张居正',
  '张释之',
  '张载',
  '周敦颐',
  '朱熹',
  '庄子',
  '子产',
] as const

const ZH_TESTER = [
  '班超',
  '扁鹊',
  '巢元方',
  '陈藏器',
  '法显',
  '甘德',
  '葛洪',
  '葛玄',
  '顾祖禹',
  '华佗',
  '皇甫谧',
  '嵇含',
  '贾耽',
  '鉴真',
  '郦道元',
  '李杲',
  '李时珍',
  '刘完素',
  '罗洪先',
  '落下闳',
  '钱乙',
  '神农',
  '石申',
  '司马承祯',
  '苏敬',
  '苏武',
  '孙思邈',
  '唐慎微',
  '陶弘景',
  '汪大渊',
  '王清任',
  '王叔和',
  '王焘',
  '王惟一',
  '吴鞠通',
  '吴又可',
  '谢肇淛',
  '徐光启',
  '徐霞客',
  '玄奘',
  '喻嘉言',
  '张从正',
  '张景岳',
  '张骞',
  '张仲景',
  '郑和',
  '周达观',
  '朱丹溪',
  '朱橚',
] as const

/* Household names from outside the artisan / jurist / explorer triad —
   emperors, generals, strategists, poets, novelists, painters. Feeds the
   Custom pool so it's the broadest cast in the system, including the
   figures most Chinese users will recognize first. */
const ZH_OTHERS = [
  '白居易',
  '蔡文姬',
  '曹操',
  '曹丕',
  '曹雪芹',
  '曹植',
  '程咬金',
  '大禹',
  '杜甫',
  '杜牧',
  '樊哙',
  '范蠡',
  '范增',
  '房玄龄',
  '勾践',
  '关汉卿',
  '关羽',
  '郭子仪',
  '汉武帝',
  '韩信',
  '忽必烈',
  '花木兰',
  '黄帝',
  '霍去病',
  '姜子牙',
  '康熙',
  '李白',
  '李广',
  '李靖',
  '李清照',
  '李煜',
  '刘邦',
  '刘备',
  '刘伯温',
  '刘秀',
  '柳永',
  '陆逊',
  '陆游',
  '罗贯中',
  '吕布',
  '吕不韦',
  '马援',
  '孟尝君',
  '孟浩然',
  '蒙恬',
  '努尔哈赤',
  '庞统',
  '平原君',
  '蒲松龄',
  '戚继光',
  '乾隆',
  '秦始皇',
  '屈原',
  '阮籍',
  '上官婉儿',
  '商汤',
  '施耐庵',
  '司马懿',
  '宋太祖',
  '苏轼',
  '苏洵',
  '苏辙',
  '孙膑',
  '孙权',
  '孙武',
  '孙中山',
  '唐太宗',
  '唐玄宗',
  '陶渊明',
  '王维',
  '卫青',
  '文天祥',
  '吴承恩',
  '吴起',
  '武则天',
  '项羽',
  '萧何',
  '萧统',
  '谢安',
  '谢灵运',
  '辛弃疾',
  '徐渭',
  '杨贵妃',
  '杨业',
  '雍正',
  '虞姬',
  '岳飞',
  '乐毅',
  '张飞',
  '张良',
  '长孙皇后',
  '张仪',
  '赵子龙',
  '周公',
  '周文王',
  '周武王',
  '周瑜',
  '朱棣',
  '诸葛亮',
  '朱元璋',
  '子贡',
  '左思',
  '左宗棠',
] as const

const EN_CUSTOM: readonly string[] = [...EN_CODER, ...EN_REVIEWER, ...EN_TESTER, ...EN_OTHERS]
const ZH_CUSTOM: readonly string[] = [...ZH_CODER, ...ZH_REVIEWER, ...ZH_TESTER, ...ZH_OTHERS]

const POOLS: Record<UiLanguage, Record<WorkerRole, readonly string[]>> = {
  en: {
    coder: EN_CODER,
    reviewer: EN_REVIEWER,
    tester: EN_TESTER,
    custom: EN_CUSTOM,
  },
  // Random worker names are playful flavor text, not translated UI copy — RU
  // reuses the EN pool rather than needing its own curated name list.
  ru: {
    coder: EN_CODER,
    reviewer: EN_REVIEWER,
    tester: EN_TESTER,
    custom: EN_CUSTOM,
  },
  zh: {
    coder: ZH_CODER,
    reviewer: ZH_REVIEWER,
    tester: ZH_TESTER,
    custom: ZH_CUSTOM,
  },
  // Random worker names are playful flavor text, not translated UI copy —
  // these Latin-alphabet locales reuse the EN pool rather than needing
  // their own curated name lists.
  es: {
    coder: EN_CODER,
    reviewer: EN_REVIEWER,
    tester: EN_TESTER,
    custom: EN_CUSTOM,
  },
  pt: {
    coder: EN_CODER,
    reviewer: EN_REVIEWER,
    tester: EN_TESTER,
    custom: EN_CUSTOM,
  },
  fr: {
    coder: EN_CODER,
    reviewer: EN_REVIEWER,
    tester: EN_TESTER,
    custom: EN_CUSTOM,
  },
  it: {
    coder: EN_CODER,
    reviewer: EN_REVIEWER,
    tester: EN_TESTER,
    custom: EN_CUSTOM,
  },
  de: {
    coder: EN_CODER,
    reviewer: EN_REVIEWER,
    tester: EN_TESTER,
    custom: EN_CUSTOM,
  },
}

const nextRandomUint32 = (): number => {
  const values = new Uint32Array(1)
  globalThis.crypto.getRandomValues(values)
  return values[0] ?? 0
}

export interface GenerateWorkerNameOptions {
  language?: UiLanguage
  role?: WorkerRole
  /* Names already taken in the current workspace. Excluded from the draw
     so the new worker doesn't collide with an existing one. Different
     workspaces are kept independent — the caller passes only its own
     workspace's names. */
  usedNames?: ReadonlySet<string>
  nextUint32?: () => number
}

export const generateWorkerName = ({
  language = 'en',
  role = 'coder',
  usedNames,
  nextUint32 = nextRandomUint32,
}: GenerateWorkerNameOptions = {}): string => {
  const pool = POOLS[language][role]
  const available =
    usedNames && usedNames.size > 0 ? pool.filter((name) => !usedNames.has(name)) : pool
  // Every role pool has dozens of figures, so exhaustion is a corner case
  // we tolerate by falling back to the full pool and accepting a duplicate
  // rather than throwing or returning an empty string.
  const draw = available.length > 0 ? available : pool
  return draw[nextUint32() % draw.length] as string
}
